/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author maka
 */
public class PickCustomerActionJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PickCustomerActionJPanel
     */
    
    EcoSystem system;
    JPanel customerProcessContainer;
    
    public PickCustomerActionJPanel(EcoSystem system, JPanel customerProcessContainer) {
        initComponents();
        this.system = system;
        this.customerProcessContainer = customerProcessContainer;
        
        this.setSize(1280, 760);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        donorSignUpBtn = new javax.swing.JButton();
        patientRegistrationBtn = new javax.swing.JButton();
        trackID = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        donorSignUpBtn.setBackground(new java.awt.Color(0, 102, 102));
        donorSignUpBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        donorSignUpBtn.setForeground(new java.awt.Color(204, 255, 204));
        donorSignUpBtn.setText("Donate");
        donorSignUpBtn.setBorder(new javax.swing.border.MatteBorder(null));
        donorSignUpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donorSignUpBtnActionPerformed(evt);
            }
        });

        patientRegistrationBtn.setBackground(new java.awt.Color(0, 102, 102));
        patientRegistrationBtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        patientRegistrationBtn.setForeground(new java.awt.Color(204, 255, 204));
        patientRegistrationBtn.setText("Request");
        patientRegistrationBtn.setBorder(new javax.swing.border.MatteBorder(null));
        patientRegistrationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientRegistrationBtnActionPerformed(evt);
            }
        });

        trackID.setBackground(new java.awt.Color(0, 102, 102));
        trackID.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        trackID.setForeground(new java.awt.Color(204, 255, 204));
        trackID.setText("Track Your Status");
        trackID.setBorder(new javax.swing.border.MatteBorder(null));
        trackID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(donorSignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(patientRegistrationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(trackID, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182)))
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(donorSignUpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientRegistrationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(trackID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void donorSignUpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donorSignUpBtnActionPerformed
        customerProcessContainer.add("DonorApplication",new DonorApplicationJPanel(system, customerProcessContainer));
        CardLayout layout = (CardLayout) customerProcessContainer.getLayout();
        layout.next(customerProcessContainer);
    }//GEN-LAST:event_donorSignUpBtnActionPerformed

    private void patientRegistrationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientRegistrationBtnActionPerformed
        customerProcessContainer.add("BloodRequest",new BloodRequestJPanel(system, customerProcessContainer));
        CardLayout layout = (CardLayout) customerProcessContainer.getLayout();
        layout.next(customerProcessContainer);
                
    }//GEN-LAST:event_patientRegistrationBtnActionPerformed

    private void trackIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackIDActionPerformed
        // TODO add your handling code here:
        customerProcessContainer.add("BloodRequest",new TrackStatusJPanel(system, customerProcessContainer));
        CardLayout layout = (CardLayout) customerProcessContainer.getLayout();
        layout.next(customerProcessContainer);
        
        
    }//GEN-LAST:event_trackIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton donorSignUpBtn;
    private javax.swing.JButton patientRegistrationBtn;
    private javax.swing.JButton trackID;
    // End of variables declaration//GEN-END:variables
}
