/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.CommonPanels.BloodRequestsListJPanel;

/**
 *
 * @author maka
 */
public class TrackStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PickCustomerActionJPanel
     */
    
    EcoSystem system;
    JPanel customerProcessContainer;
    
    public TrackStatusJPanel(EcoSystem system, JPanel customerProcessContainer) {
        initComponents();
        this.system = system;
        this.customerProcessContainer = customerProcessContainer;
        
        this.setSize(1280, 760);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        btnTrackRequests = new javax.swing.JButton();
        btnTrackApplications = new javax.swing.JButton();
        logo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 153));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        btnBack.setText("<< Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnTrackRequests.setText("Track Blood Requests");
        btnTrackRequests.setBorder(new javax.swing.border.MatteBorder(null));
        btnTrackRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackRequestsActionPerformed(evt);
            }
        });

        btnTrackApplications.setText("Track Donor Applications");
        btnTrackApplications.setBorder(new javax.swing.border.MatteBorder(null));
        btnTrackApplications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackApplicationsActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/world-cord-logo.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(65, 65));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrackApplications, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTrackRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(671, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrackRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTrackApplications, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        customerProcessContainer.remove(this);
        CardLayout layout = (CardLayout) customerProcessContainer.getLayout();
        layout.previous(customerProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnTrackRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackRequestsActionPerformed
        customerProcessContainer.add("BloodRequest",new TrackBloodRequestsListJPanel(system, customerProcessContainer));
        CardLayout layout = (CardLayout) customerProcessContainer.getLayout();
        layout.next(customerProcessContainer);
    }//GEN-LAST:event_btnTrackRequestsActionPerformed

    private void btnTrackApplicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrackApplicationsActionPerformed
        // TODO add your handling code here:
        customerProcessContainer.add("BloodRequest",new TrackingDonorApplicationListJPanel(system, customerProcessContainer));
        CardLayout layout = (CardLayout) customerProcessContainer.getLayout();
        layout.next(customerProcessContainer);
        
        
    }//GEN-LAST:event_btnTrackApplicationsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTrackApplications;
    private javax.swing.JButton btnTrackRequests;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
